workflows:
  android-workflow:
    name: Android APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Generate Android platform files
        script: flutter create . --platforms=android --project-name pdf_audiobook --org com.pdfaudiobook
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
